<a href="https://colab.research.google.com/github/Brayan-Garcia-Lopez/Metodos-Numericos/blob/main/unidad_5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#tabla de diferencias divididas
import numpy as np

x = np.array([1,2,3]) #define los valores de x conocidos
y = np.array([1,4,9]) #define los valores de y correspondientes

n = len(x) #Calcula el numero de puntos

tabla = np.zeros((n,n)) #Inicializa la tabla de diferencias divididas


tabla[:,0] = y #Llena la primera columna con valores de y

for j in range(1,n): #Itera sobre las columnas de la tabla
  for i in range(n-j): #Itera sobre las filas disponibles
    tabla[i,j] = (tabla[i+1,j-1] - tabla[i,j-1])/(x[i+j] - x[i]) #calcula la diferencia


print("Tabla de diferencias divididas: \n",tabla) #Muestra la tabla

Tabla de diferencias divididas: 
 [[1. 3. 1.]
 [4. 5. 0.]
 [9. 0. 0.]]


In [ ]:
#Evaluacion de polinomio de newtoon

x = np.array([1,2,3]) #define los valores de x conocidos
y = np.array([1,4,9]) #define los valores de y correspondientes

n = len(x) #Calcula el numero de puntos

tabla = np.zeros((n,n)) #Inicializa la tabla de diferencias divididas


tabla[:,0] = y #Llena la primera columna con valores de y

for j in range(1,n): #Itera sobre las columnas de la tabla
  for i in range(n-j): #Itera sobre las filas disponibles
    tabla[i,j] = (tabla[i+1,j-1] - tabla[i,j-1])/(x[i+j] - x[i]) #calcula la diferencia


def newton_eval(x_data, tabla, x_val): #Define funcion para evaluar el polinomio
  n = len(x_data) #numero de puntos
  resultado = tabla[0,0] #Inicializa el primer coeficiente

  producto = 1 #Inicializa el producto acumulado

  for i in range(1,n): #Itera sobre terminos del polinomio
    producto *= (x_val - x_data[i-1]) #Calcula el termino (x-x_i)
    resultado += tabla[0,i]*producto #Suma el termino correspondiente

  return resultado #Retorna valor interpolado

valor = newton_eval(x,tabla,2.5) #Evalua el polinomio en x=2.5

print("Valor Interpolado:",valor) #Muestra resultado

Valor Interpretado: 6.25


In [ ]:
#Aplicaion IA:Interpolacion de datos

x = np.array([0,1,2,3]) #define los valores de x conocidos
y = np.array([1,2,0,5]) #define los valores de y correspondientes

n = len(x) #Calcula el numero de puntos

tabla = np.zeros((n,n)) #Inicializa la tabla de diferencias divididas


tabla[:,0] = y #Llena la primera columna con valores de y

for j in range(1,n): #Itera sobre las columnas de la tabla
  for i in range(n-j): #Itera sobre las filas disponibles
    tabla[i,j] = (tabla[i+1,j-1] - tabla[i,j-1])/(x[i+j] - x[i]) #calcula la diferencia


def newton(x_data, tabla, x_val): #Define funcion para evaluar el polinomio
  n = len(x_data) #numero de puntos
  resultado = tabla[0,0] #Inicializa el primer coeficiente
  producto = 1

  for i in range(1,n): #Itera sobre terminos del polinomio
    producto *= (x_val - x_data[i-1]) #Calcula el termino (x-x_i)
    resultado += tabla[0,i]*producto #Suma el termino correspondiente

  return resultado #Retorna valor interpolado

x_interp = 1.5 #punto donde se quiere estimar el valor

y_interp = newton(x,tabla,x_interp) #Interpolacion

print("Valor estimado: ",y_interp) #Resultado final

Valor estimado:  0.75


In [ ]:
#Implementacion basica de langrage

import numpy as np

x = np.array([0,1,2,3]) #define los valores de x conocidos
y = np.array([1,2,0,5]) #define los valores de y correspondientes


def langrage(x_data, y_data, x_val): #Define funcion de interpolacion de langrage
  n = len(x_data) #Obtiene el numero de puntos
  resultado = 0 #Inicializa el resultado del polinomio

  for i in range(n):#Itera sobre cada punto
    L = 1 #Inicializa el polinomio base l_i

    for j in range(n): #Itera sobre todos los puntos para construir l_i
      if j != i: #Evita dividir entre 0 cuando i=j
        L *= (x_val - x_data[j])/(x_data[i] - x_data[j]) #Calcula el polinomio

    resultado += y_data[i] #Acumula el termino correspondiente al polinomio
  return resultado #Retorna el valor interpolado

valor = langrage(x,y,2.5) #Evalua el polinomio en x=2.5

print("Valor interpolado: ",valor)



Valor interpolado:  8


In [ ]:
#Comparacion con funcion real

def f(x):
  return x**2

x = np.array([1,2,3])
y = f(x)

def langrage(x_data, y_data, x_val): #Define funcion de interpolacion de langrage
  n = len(x_data) #Obtiene el numero de puntos
  resultado = 0 #Inicializa el resultado del polinomio

  for i in range(n):#Itera sobre cada punto
    L = 1 #Inicializa el polinomio base l_i

    for j in range(n): #Itera sobre todos los puntos para construir l_i
      if j != i: #Evita dividir entre 0 cuando i=j
        L *= (x_val - x_data[j])/(x_data[i] - x_data[j]) #Calcula el polinomio

    resultado += y_data[i] #Acumula el termino correspondiente al polinomio

  return resultado #Retorna el valor interpolado

x_test = 2.5
interp = langrage(x,y,x_test)
real = f(x_test)
error = abs(real - interp)

print("Interpolado:", interp)
print("Real: ",real)
print("Error:",error)

Interpolado: 14
Real:  6.25
Error: 7.75


In [ ]:
#Aplicacion IA: Reconstruccion de datos

x = np.array([0,1,2,3]) #Datos en x (Pueden ser tiempos o features)
y = np.array([1,3,2,5]) #Datos observados(Pueden tener ruido)

def langrage(x_data, y_data, x_val): #Define funcion de interpolacion de langrage
  n = len(x_data) #Obtiene el numero de puntos
  resultado = 0 #Inicializa el resultado del polinomio

  for i in range(n):#Itera sobre cada punto
    L = 1 #Inicializa el polinomio base l_i

    for j in range(n): #Itera sobre todos los puntos para construir l_i
      if j != i: #Evita dividir entre 0 cuando i=j
        L *= (x_val - x_data[j])/(x_data[i] - x_data[j]) #Calcula el polinomio

    resultado += L * y_data[i] #Acumula el termino correspondiente al polinomio. Fixed the missing L * here.

  return resultado #Retorna el valor interpolado

x_interp = 1.5


y_interp = langrage(x,y,x_interp)

print("Valor estimado",y_interp)

#Permite construir modelos exactos apartir de datos es intuitiva y directa util en datset pequeños base para metodos mas avanzados

Valor estimado 2.4375


In [ ]:
#interpolacion segmentada(spline)
import numpy as np
from scipy.interpolate import CubicSpline

x = np.array([0,1,2,3])#deine los puntos en el eje x
y = np.array([1,3,2,5]) #Define los valores correspondientes en y

scpline = CubicSpline(x,y) #Construye scpline cubico que interpola los puntos

x_interp = np.linspace (0,3,100)

y_interp = scpline(x_interp)

print("Valores interpolados:",y_interp)

Valores interpolados: [1.         1.17220877 1.33542959 1.48985725 1.63568653 1.77311221
 1.90232908 2.02353192 2.13691553 2.24267468 2.34100416 2.43209877
 2.51615327 2.59336246 2.66392112 2.72802404 2.78586601 2.8376418
 2.88354621 2.92377401 2.95852    2.98797896 3.01234568 3.03181494
 3.04658152 3.05684021 3.0627858  3.06461307 3.06251681 3.0566918
 3.04733283 3.03463468 3.01879215 3.         2.97845303 2.95434603
 2.92787378 2.89923106 2.86861266 2.83621337 2.80222797 2.76685125
 2.73027799 2.69270297 2.65432099 2.61532682 2.57591526 2.53628108
 2.49661908 2.45712404 2.41799074 2.37941397 2.34158852 2.30470917
 2.2689707  2.2345679  2.20169556 2.17054846 2.14132139 2.11420913
 2.08940646 2.06710818 2.04750907 2.03080391 2.01718749 2.00685459
 2.         1.99681851 1.99750489 2.00225394 2.01126045 2.02471918
 2.04282494 2.06577251 2.09375667 2.1269722  2.1656139  2.20987654
 2.25995492 2.31604382 2.37833802 2.44703231 2.52232147 2.60440029
 2.69346356 2.78970606 2.89332257 3.004507

In [ ]:
#Regresion lineal
x = np.array([1,2,3,4,5])
y = np.array([2,4,5,4,5])

coef = np.polyfit(x,y,1)

m = coef[0]
b = coef[1]

y_pred = m*x + b

print("Pendiente:",m)
print("Intercepto:",b)
print("Prediccion:",y_pred)

Pendiente: 0.6000000000000001
Intercepto: 2.1999999999999997
Prediccion: [2.8 3.4 4.  4.6 5.2]


In [ ]:
#Correlacion
x = np.array([1,2,3,4,5])
y = np.array([2,4,5,4,5])

correlacion = np.corrcoef(x,y)[0,1]

print("Coeficicnetes de correlacion: ",correlacion)

Coeficicnetes de correlacion:  0.7745966692414834


In [ ]:
#Regresion lineal ccon minimos cuadrados(Manual)
import numpy as np

x = np.array([1,2,3,4,5]) #Define los datos de entrada
y = np.array([2,4,5,4,5]) #define los datos observados

X = np.vstack([np.ones(len(x)), x]).T #Construye la matriz de diseño con columnas

XT = X.T #Calcula .a transpuesta de la mariz X

beta = np.linalg.inv(XT.dot(X)).dot(XT).dot(y) #Aplica la formula de minimos cuadrados

b = beta[0] #Extrae el intercepto
m = beta[1] #Extrae la pendiente

y_pred = m*x+b #Calcula los valores estimados para el modelo

print("Pendiente",m) #Muestra la pendeinte
print("intercepto",b) #Muestra el intercepto
print("Prediccion",y_pred) #Muestra la prediccion

Pendiente 0.6000000000000002
intercepto 2.2000000000000046
Prediccion [2.8 3.4 4.  4.6 5.2]


In [ ]:
#Ajuste polinomial
x = np.array([1,2,3,4,5]) #Define los datos de entrada
y = np.array([2,4,5,4,5]) #define los datos observados

coef = np.polyfit(x,y,2)  #Ajuste polinomial de grado 2

a = coef[0] # Coeficiente cuadratico
b = coef[1] # Coeficinte lineal
c = coef[2] # Termino Independiente

y_pred = a*x**2 + b*x + c #Calcula valores predichos

print("Coeficientes",coef) #Muestra coeficientes
print("Prediccion",y_pred) #Muestra el ajuste

Coeficientes [-0.28571429  2.31428571  0.2       ]
Prediccion [2.22857143 3.68571429 4.57142857 4.88571429 4.62857143]


In [ ]:
#Error cuadratico medio(MSE)

x = np.array([1,2,3,4,5]) #Define los datos de entrada
y = np.array([2,4,5,4,5]) #define los datos observados

coef = np.polyfit(x,y,1) #Ajuste  lineal

y_pred = coef[0]*x + coef[1] #Predicciones

error = np.mean((y - y_pred)**2) #calculla el error cuadratico

print("Error MSE", error) #Muestra el error

Error MSE 0.47999999999999987
